# Generated by Django 2.0.2 on 2018-04-02 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empregador', '0001_initial'),
        ('candidato', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candiato', to='candidato.Candidato')),
            ],
        ),
        migrations.CreateModel(
            name='Requisitos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requisito', models.TextField(max_length=300, verbose_name='Requisito')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=50, verbose_name='Função')),
                ('descricao', models.TextField(max_length=1000, verbose_name='Descrição das Atividades')),
                ('confidencial', models.BooleanField(default=False, verbose_name='Confidencial')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('ultima_modificacao', models.DateTimeField(auto_now=True, verbose_name='Última Modificação')),
                ('status', models.BooleanField(default=True, verbose_name='Está ativa?')),
                ('finalizada', models.BooleanField(default=False, verbose_name='Foi finalizada?')),
                ('salario', models.CharField(blank=True, max_length=20, verbose_name='Salário')),
                ('local', models.CharField(max_length=50, verbose_name='Cidade')),
                ('escolaridade', models.CharField(blank=True, choices=[('', ''), ('Fundamental incompleto', 'Fundamental incompleto'), ('Fundamental completo', 'Fundamental completo'), ('Medio incompleto', 'Médio incompleto'), ('Medio completo', 'Médio completo'), ('Tecnico incompleto', 'Técnico incompleto'), ('Tecnico completo', 'Técnico completo'), ('Superior incompleto', 'Superior incompleto'), ('Superior completo', 'Superior completo'), ('Pos-Graduacao', 'Pós-Graduação'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado'), ('PHD', 'PHD')], max_length=25, null=True, verbose_name='Escolaridade exigida')),
                ('empregador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empregador', to='empregador.Empregador')),
            ],
        ),
        migrations.AddField(
            model_name='requisitos',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaga_requisito', to='vagas.Vaga'),
        ),
        migrations.AddField(
            model_name='candidatura',
            name='vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaga', to='vagas.Vaga'),
        ),
    ]
