# Generated by Django 2.0.2 on 2018-04-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaga',
            name='inscritos',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade de inscritos'),
        ),
    ]
