# Generated by Django 2.0.2 on 2018-04-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0003_auto_20180403_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='salario',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Salário'),
        ),
    ]
