# Generated by Django 2.0.2 on 2018-04-10 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidato', '0002_candidato_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profissoes',
            options={'ordering': ['nome_prof'], 'verbose_name': 'Profissão', 'verbose_name_plural': 'Profissões'},
        ),
    ]
