# Generated by Django 2.0.2 on 2018-04-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empregador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=18, verbose_name='CNPJ')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome Fantasia')),
                ('ramo', models.CharField(blank=True, choices=[('', ''), ('Industria', 'Indústria'), ('Comercio', 'Comércio'), ('Prestacao de Servicos', 'Prestação de Serviços'), ('Outros', 'Outros')], max_length=25, null=True, verbose_name='Ramo de Atividade')),
                ('tipo', models.CharField(blank=True, choices=[('', ''), ('MEI', 'MEI - Faturamento até R$ 81 mil'), ('ME', 'ME - Faturamento até R$ 360 mil'), ('EPP', 'EPP - Faturamento até R$ 3,6 milhões'), ('Empresa Normal', 'Empresa Normal - Faturamento superior a R$ 3,6 milhões')], max_length=25, null=True, verbose_name='Tipo da Empresa')),
                ('tel1', models.CharField(blank=True, max_length=12, null=True, verbose_name='Tel(1)')),
                ('tel2', models.CharField(blank=True, max_length=12, null=True, verbose_name='Tel(2)')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço')),
                ('numeroLog', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=50, null=True, verbose_name='Bairro')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('cep', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('cidade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cidade')),
                ('uf', models.CharField(blank=True, max_length=50, null=True, verbose_name='UF')),
            ],
        ),
    ]
